### ISSUE TITLE
tunneling: .NET example project validation

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/examples#111]
Update the [.NET tunneling example](https://github.com/getsentry/examples/tree/master/tunneling/dotnet) to validate project IDs similar to how [the Python example](https://github.com/getsentry/examples/blob/0ee7bc0a9eed3624a482e1bf51eef1e77d26f1a9/tunneling/python/app.py#L29-L30) does.

**Comment by bruno-garcia** [comment]
To clarify the motivation: the project validation will ensure no one can use your backend as an open tunnel (so they can also bypass ad-blockers without having to tunnel things themselves).

**Comment by armcknight** [comment]
If it's still needed, let's focus the efforts in https://github.com/getsentry/sentry-dotnet moving forward.
