### ISSUE TITLE
Android sentry doesn't minify.

### ISSUE THREAD

**Issue by Xiaoben336** [getsentry/examples#116]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io).

Which SDK and version?
Android 5.3.0

### Steps to Reproduce

I am using your sample android project. I have replaced the sample dsn with dsn from my project settings.
Although minifyEnabled is set to true for the release build type in build.gradle, the code is not actually minified by parsing the apk.
So I create a new module named mylibrary, and the code in the module was successfully minified.
I mocked a null pointer exception, after uploading the crash log to Sentry, I found that the code was minified.

The mapping file has been uploaded to ProGuard Mappings.
![image](https://user-images.githubusercontent.com/19324261/143804677-6f3dc6e4-8643-4d3d-a104-ca4514207b6a.png)

### Actual Result
![image](https://user-images.githubusercontent.com/19324261/143804377-7818e16a-0239-464e-9138-db2e2575014b.png)

**Comment by bruno-garcia** [comment]
The stacktrace itself is unminified:
![image](https://user-images.githubusercontent.com/1633368/143919033-af83e914-3337-47dd-acbc-0952c77f8f4c.png)


The message isn't, as Sentry isn't aware there's a stack trace in there. All it knows is that it's a string message

**Comment by bruno-garcia** [comment]
The issue tracking this is here: https://github.com/getsentry/sentry-java/issues/1086
