### ISSUE TITLE
Cannot access 'url' before initialization

### ISSUE THREAD

**Issue by mikey-mo** [getsentry/examples#131]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
@sentry/nextjs 6.12.0

### Steps to Reproduce

1. Pull example NextJS project
2. Install dependencies
3. Open Console
4. See 400 Response from `<url>/api/tunnel`

### Expected Result

API should consume request without error

### Actual Result

API errors because of a constant, `url`.

`/pages/api/tunnel`
```
import * as url from 'url';

---

const url = `https://${sentryHost}/api/${projectId}/envelope/`;

```
Which results in error log:

```
ReferenceError: Cannot access 'url' before initialization
```

**Comment by callum-gander** [comment]
Also getting this error, did you solve it? Or does anyone from Sentry have any suggestions?

**Comment by myxoh** [comment]
I wouldn't trust this sampel code - they are using a legacy API anyway.

I did the following instead:

```js
    const dsnUrl = new URL(header.dsn);
    const host = dsnUrl.host;
    const path = dsnUrl.pathname
```
and remove the import for `url`

Some other changes were:
in my case the `projecrUrl` had ` /` at the beginning of the path (as that's how `pathname` works) - this also happened on their sample code so I changed to:

```js
    const dsnUrl = new URL(header.dsn);
    const host = dsnUrl.host;
    const path = dsnUrl.pathname.slice(1, -1);
```

Finally in my case I had to add an await on the `.json()` call at the end to avoid the request hanging on the `tunnel` (`json()` is a promise)

```js
    const response = await fetch(errorUrl, {
      method: "POST",
      body: envelope,
    });
    const jsonResponse = await response.json();
    return jsonResponse;
```

**Comment by AbhiPrasad** [comment]
If you upgrade to Next.js SDK `7.26.0` or higher (we recommend using latest) you can use the `tunnelRoute` option to automatically set up a tunnel. We recommend you use this option for tunneling instead of setting up your own.

See the docs: https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/#configure-tunneling-to-avoid-ad-blockers

```js
// next.config.js
const nextConfig = {
  sentry: {
    tunnelRoute: "/monitoring-tunnel",
  },
};
```

Closing this issue for repo cleanup - please let us know if this still applies. Thanks!
