### ISSUE TITLE
Tunneling on nextjs > TypeError: Invalid URL

### ISSUE THREAD

**Issue by angelod1as** [getsentry/examples#151]
## Summary

When I add tunneling, my app does not serve or build — it gives an error `TypeError: Invalid URL` — thus, I can't continue testing if my tunneling is properly configured and if it should work.

### Environment

`@sentry/nextjs: 7.14.1`
`next: 12.3.1`

I use Sentry SaaS (sentry.io)

### Steps to Reproduce

1. Following the [tunneling example](https://github.com/getsentry/examples/tree/master/tunneling/nextjs)...
2. I added the `tunnel` prop to `Sentry.init` (code below)
3. I created the `/api/sentry` file (code below)

### Expected Result

Serve and build the project successfully (and keep on testing the Tunnel without issue)

### Actual Result

When serving or building the project, I get a `TypeError`:

On Terminal:

```
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at Object.makeNodeTransport [as transport] (/Users/angelo/Documents/GIT/autoservice-frontend/node_modules/@sentry/node/cjs/transports/http.js:34:21)
    at new BaseClient (/Users/angelo/Documents/GIT/autoservice-frontend/node_modules/@sentry/core/cjs/baseclient.js:71:33)
    at new NodeClient (/Users/angelo/Documents/GIT/autoservice-frontend/node_modules/@sentry/node/cjs/client.js:45:5)
    at Object.initAndBind (/Users/angelo/Documents/GIT/autoservice-frontend/node_modules/@sentry/core/cjs/sdk.js:34:16)
    at Object.init (/Users/angelo/Documents/GIT/autoservice-frontend/node_modules/@sentry/node/cjs/sdk.js:154:8)
    at Object.init (/Users/angelo/Documents/GIT/autoservice-frontend/node_modules/@sentry/nextjs/cjs/index.server.js:62:8)
    at eval (webpack-internal:///./sentry.client.config.js:75:45) {
  input: '/api/sentry',
  code: 'ERR_INVALID_URL'
}
```

On Browser:
<img width="735" alt="image" src="https://user-images.githubusercontent.com/13950513/194872861-6a2f5b4b-c3e6-49da-88b9-78d13bb8cb27.png">

### Notes

This might be related to #131 but as the message is different, I preferred to open a new issue.

### Code

```js
// sentry.client.config.js

import * as Sentry from "@sentry/nextjs"

export const sentryConfig = {
  dsn: process.env.SENTRY_DSN,
  release: process.env.SENTRY_RELEASE,
  environment: process.env.SENTRY_ENVIRONMENT,
  sampleRate: 1.0,
}

Sentry.init({
  ...sentryConfig,
  tunnel: "/api/sentry",
})
```

```ts
// /api/sentry.ts

// Change host appropriately if you run your own Sentry instance.
const sentryHost = process.env.SENTRY_HOST

// Set knownProjectIds to an array with your Sentry project IDs which you
// want to accept through this proxy.
const knownProjectIds: string[] = [process.env.SENTRY_PROJ_ID]

const handler: NextApiHandler = async (req, res) => {
  try {
    const envelope = req.body
    const pieces = envelope.split("\n")

    const header = JSON.parse(pieces[0])

    const { host, pathname } = new URL(header.dsn)

    if (host !== sentryHost) {
      throw new Error(`invalid host: ${host}`)
    }

    if (!pathname) {
      throw new Error(`invalid pathname`)
    }

    const projectId = pathname.replace(/\//g, "")

    if (!knownProjectIds.includes(projectId)) {
      throw new Error(`invalid project id: ${projectId}`)
    }

    const finalUrl = `https://${sentryHost}/api/${projectId}/envelope/`

    const response = await fetch(finalUrl, {
      method: "POST",
      body: envelope,
    })

    return await response.json()
  } catch (e) {
    captureException(e)
    return res.status(400).json({ status: e })
  }
}

export default withSentry(handler)
```

**Comment by itsmingjie** [comment]
A speculation may be that your environment variables may not be accessible on the client side. Public variables for next.js must start with `NEXT_PUBLIC_`

**Comment by angelod1as** [comment]
@itsmingjie That's correct if you are hosting it on Vercel, which we are not.

**Comment by itsmingjie** [comment]
> @itsmingjie That's correct if you are hosting it on Vercel, which we are not.

That is not the case. See docs: https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser: 

> By default environment variables are only available in the Node.js environment, meaning they won't be exposed to the browser. ... This inlining occurs at build time, so your various NEXT_PUBLIC_ envs need to be set when the project is built.

This is due to how Next.js builds your APIs, which is independent from where you're hosting it.

**Comment by angelod1as** [comment]
@itsmingjie hmmm good, thanks for that resource. I'll talk with the devops people in my project to see if we're missing that point.

**Comment by AbhiPrasad** [comment]
If you upgrade to Next.js SDK `7.26.0` or higher (we recommend using latest) you can use the `tunnelRoute` option to automatically set up a tunnel. We recommend you use this option for tunneling instead of setting up your own.

See the docs: https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/#configure-tunneling-to-avoid-ad-blockers

```js
// next.config.js
const nextConfig = {
  sentry: {
    tunnelRoute: "/monitoring-tunnel",
  },
};
```

Closing this issue for repo cleanup - please let us know if this still applies. Thanks!
