### ISSUE TITLE
Does Android still need an auth token etc?

### ISSUE THREAD

**Issue by julianharty** [getsentry/examples#169]
### Environment

Android Studio using your current Android app example.

The project includes https://github.com/getsentry/examples/tree/master/android which has [sentry.properties](https://github.com/getsentry/examples/blob/master/android/sentry.properties) However this isn't mentioned as far as I can tell in your public documentation for Android https://docs.sentry.io/platforms/android/ or https://docs.sentry.io/platforms/android/configuration/manual-init/

When I checked https://sentry.io/settings/account/api/auth-tokens/ I don't get the impression that I should use auth-tokens for an Android app. Please can you clarify what's required and - if necessary - revise and update your example Android app please?

### Steps to Reproduce

1. Checked out this examples repo.
2. Compared the code with your public docs.

### Expected Result

The sample Android app would match the docs.

### Actual Result

They don't match.

**Comment by armcknight** [comment]
Hi @julianharty , sorry for the late reply on this issue. We are going to deprecate and eventually archive this repo, please check out https://github.com/getsentry/sentry-java/tree/main/sentry-samples for android samples and file issues on that repo going forward for these kinds of questions. Hope things worked out for you in the meantime! Thanks 🙏🏻
