### ISSUE TITLE
[JavaScript] New JS Tunneling Example

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/examples#184]
Now that tunneling is a breeze in nextJS we should consider making a verbose JS example using basic node request/response object to illustrate how this is done in a way that respects all event types (including replays).

**Comment by souredoutlook** [comment]
cc @lforst

**Comment by armcknight** [comment]
Let's figure out if we can add this in either/both https://github.com/sentry-demos or https://github.com/getsentry/sentry-javascript (or even https://github.com/vercel/next.js/tree/canary/examples/with-sentry).
