### ISSUE TITLE
Android sentry doesn't work

### ISSUE THREAD

**Issue by BulatMukhutdin** [getsentry/examples#36]
I am using your sample android project. I have replaced the sample dsn with dsn from my project settings. But i don't receive any issues

**Comment by AlexRU18** [comment]
same error

**Comment by marandaneto** [comment]
hey @BulatMukhutdin and @AlexRU18 I've just updated the Android sample to our brand new Android SDK, please check it out and raise a new issue if you find any issues.

#40

Thanks :)
