### ISSUE TITLE
Links broken 404 for Logback Config in Spring-Boot Example

### ISSUE THREAD

**Issue by frostyandy2k** [getsentry/examples#37]
Links broken for Logback Config in Spring-Boot Example:

https://github.com/getsentry/examples/tree/master/java/spring-boot

Here:
> See src/main/resources/logback.xml for example logger configuration and pom.xml for the dependency on io.sentry:sentry-logback.

**Comment by bruno-garcia** [comment]
We have a new major, will redo the example through #67
