### ISSUE TITLE
Missing await in Azure Functions node example

### ISSUE THREAD

**Issue by empz** [getsentry/examples#71]
The docs correctly shows how to capture and flush a handled exception inside an Node Azure Function.

The example in this repo doesn't await the `Sentry.flush` method.

https://github.com/getsentry/examples/blob/b6ba4611a62f8b182cccf726121b74359e62c949/azure-functions/node/handled_exception/index.js#L26

**Comment by bruno-garcia** [comment]
Thanks for pointing out @empz
