### ISSUE TITLE
Add example for cordova with tracing support

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/examples#81]
[Came up on Discord:](https://discord.com/channels/621778831602221064/816438007921377361/834743708540731402)

> Hi.  The latest release of the SDK says that it supports transaction tracing from the client.  Its pretty light on the details.  are there any guides on how to add this to an Ionic / Cordova app?

Relates [to the sample in the repo](https://github.com/getsentry/sentry-cordova/issues/206), but these examples are using the package through the package manager and have the goal to show to users how they can do things, explained in a readme. We can link to examples here from the docs and when they ask us on discord/forum/stackoverflow

**Comment by bruno-garcia** [comment]
And on Twitter: https://twitter.com/thatsmekaustubh/status/1389642193871147009

**Comment by armcknight** [comment]
If this is still needed and hasn't already been done, let's add it to https://github.com/getsentry/sentry-cordova.
