### ISSUE TITLE
Tracing Example for Azure Functions (and other serverless?)

### ISSUE THREAD

**Issue by derekrprice** [getsentry/examples#87]
I attempted to enable tracing in my serverless application, but we have a high traffic application, which means that many invocations of both the same function and other functions are often running in parallel.  Since the Sentry.configureScope() call is global, attempting to set a span for one instance overwrites spans enabled for previous instances.  If there is a way to configure a separate scope for each function invocation, it should be documented, both in Sentry's Azure Functions SDK docs and in this examples repository.

**Comment by derekrprice** [comment]
I think this may need more than documentation.  I've created a bugd report at https://github.com/getsentry/sentry-javascript/issues/3572

**Comment by bruno-garcia** [comment]
Agreed this is something best fit to raise in the SDK repo. Thanks for raising there.
